"""trends, explanations and briefs

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 09:00:16.732435
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'done', 'failed', name='reportstatus', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_briefs_person_key'), ['person_key'], unique=False)

    op.create_table('explanations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'done', 'failed', name='reportstatus', native_enum=False, length=20), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'language')
    )
    with op.batch_alter_table('explanations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_explanations_report_id'), ['report_id'], unique=False)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_key', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_reports_person_key'), ['person_key'], unique=False)

    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalog_key', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('std_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('std_low', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('std_high', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_test_results_catalog_key'), ['catalog_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_results_catalog_key'))
        batch_op.drop_column('std_high')
        batch_op.drop_column('std_low')
        batch_op.drop_column('std_value')
        batch_op.drop_column('catalog_key')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_person_key'))
        batch_op.drop_column('person_key')

    with op.batch_alter_table('explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_explanations_report_id'))

    op.drop_table('explanations')
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_briefs_person_key'))

    op.drop_table('briefs')
    # ### end Alembic commands ###
