"""accounts, family profiles and sessions

Every report now belongs to a family profile owned by a signed-in user.
Reports saved before this have no owner, and nobody could see them anymore,
so they are deleted here (only local sample data existed before Phase 3).
Their files stay in the uploads folder and can be deleted by hand.

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-05 09:23:09.348326
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('relation', sa.Enum('self', 'spouse', 'parent', 'child', 'sibling', 'grandparent', 'other', name='relation', native_enum=False, length=20), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    for table in ('briefs', 'explanations', 'test_results', 'reports'):
        op.execute(sa.text(f'DELETE FROM {table}'))

    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.String(length=36), nullable=False))
        batch_op.drop_index(batch_op.f('ix_briefs_person_key'))
        batch_op.create_index(batch_op.f('ix_briefs_profile_id'), ['profile_id'], unique=False)
        batch_op.create_foreign_key('fk_briefs_profile_id_profiles', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('person_key')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.String(length=36), nullable=False))
        batch_op.drop_index(batch_op.f('ix_reports_person_key'))
        batch_op.create_index(batch_op.f('ix_reports_profile_id'), ['profile_id'], unique=False)
        batch_op.create_foreign_key('fk_reports_profile_id_profiles', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('person_key')

    # ### end Alembic commands ###


def downgrade() -> None:
    # Reports can't go back to having no owner, so the downgrade empties them too.
    for table in ('briefs', 'explanations', 'test_results', 'reports'):
        op.execute(sa.text(f'DELETE FROM {table}'))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_key', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('fk_reports_profile_id_profiles', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reports_profile_id'))
        batch_op.create_index(batch_op.f('ix_reports_person_key'), ['person_key'], unique=False)
        batch_op.drop_column('profile_id')

    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_key', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint('fk_briefs_profile_id_profiles', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_briefs_profile_id'))
        batch_op.create_index(batch_op.f('ix_briefs_person_key'), ['person_key'], unique=False)
        batch_op.drop_column('profile_id')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_user_id'))

    op.drop_table('profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
